2021-01-06 17:59:33,117 ERROR __init__.py <module> 16 - 测试日志器能不能正常工作
